POST http://localhost:8080/papagoApi/detectLang
Content-Type: application/json

{
  "text": "hello"
}

###
POST http://localhost:8080/papagoApi/detectLang
Content-Type: application/json

{
  "text": "안녕"
}

###
